[gcp_service_account]
# paste EXACTLY the fields from your downloaded JSON below:
type = "service_account"
project_id = "pnany-fall-conference-2025"
private_key_id = "40b2b584f98b29dfb7cd81f9a501a7f5bcaa0da6"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDX/9GQX+pWE2bk\nOf7N9u/9LnVX0RlsXQyy8TskezpHxsYDyl870Vw+3gJDiX/Kz3K9EqluLwQKQkBl\nSDJiOHCE+gYGo1BEMyCw6S+7c1JvYlsHVHoHk8/slNhCTjAuq3m6MN5kvTtpDhkH\n0wIfjSB9pEoVp0HnXUmkp9EpjMsUeStOMRiRbWu9g59lJppsrl1sOeIRgAaiWcyO\nQJzjgSbWWdEVBomYA3r5aH5/6bysvyRV2N25yQxPjL8xVPlix5iwSyBnY8L84f77\nPP1bij9wiTkUILiy+U8VH/2jhq8jEFJbloaAv3ippeVBwxY+NPCrKrG3Bvr19jF0\n3RmMlO5/AgMBAAECggEABocEEb1cSwqeDuKTySyftwJ66FL41jX/pr60f1c7/SRM\nIpwwgZHDnGDAJ8NVec8IFB+mwB4qnJbA9G6YmzBCcjpOCVBRIiZ7Y+1AFIWZJaWO\nw6txXp5AZ9Fdsa9ENHzZGl/UsK2pSHT1G6/sPgDZTQK0fHAIBVJj4dZyczN+hZlP\nkh2bPov/X+YxUp7WAQJqOot9QOUMRi7rWOT/6x8n4iXakE4kXkHSWQjtN04Vr2aU\nZs2HxJLK5yJihDEtDNf0mMp9/gwUFQEIWg81NhuiLSgs8KtQDE4XbpwRRNfoId0o\nfB1MOjFvM2s9JArPiiOerE42yMEGowVN6bO2vqwfdQKBgQD4rd36V9wKgTqGzrCw\nuuF5rbZLBBYmA/vxftoRGP2dNbC22ItX+RO/R8P2azuribaMI17MAtn6ugrajiqQ\nFO60PbQmhCSUlPZL1nK9oNjqSXC0g3fSnv4B1ugOLE2u6YzzK6ZBjaRoSFG4Tcnh\nD3CqvtYEyauMaGJ30snLjbu4lQKBgQDeW6og2tp8ll8KptssFvT+gZqwZwRByt8t\nOqhtqGEnWbsK1W8mc+7Qlob2kYGq1EeibIYEQhMip+PJzlBRY27XjeqzPenq21XX\nUx9EaA0BjGPtvQcqgZOKKcuhiIVVDI7EKz+n1b4juTvNZLHYceWU+blLBELB2vJq\nuAiEr/PBwwKBgBriSQYga3RjRh1+yNFCUs/hvLxdY7uWYK1Z5l9E0V4miMUrodzP\n25epPYEtVJUV3TtHM59gi4o0hKneBrHu4WNw7EHhtUau1/WY6Gyhr/GcIOgS8mg9\nsf4m6o1lsrw/GXLMfDvIAUcY0mTXXATNs4NyABciaj5SppqHmjM8TlgFAoGAd+8v\nS3tgP7UH3IH1U8mqKaCUZDOcizQ2vnmWIVeh14zBo21N/4qmtGGMuG/xZcgMP2KT\nwrY1BgtShSZAEjY0shV9E2MAycm2emb+RXJuGXi06aV8uQOdJfe3OxCdAiu80biW\nJBvY7AHcbMO0XY/JilpMBFdu/orvGHrdNVyGeOsCgYEAzB8Fg3rUDQpYBHpRPZCm\nZEYAt0S3lWa2KcWUgsSEegdfghuq+Y+UQsaJ6YBsJB309Zdag6Zx2aKeU4eviDBc\nAzRE+a/qPGNGglEctIpPNqOCYTPEW3t8VqDOryjdkDNJRekUR6T9r5tXAZQ6VwRP\nV4/rAeeVak+kZ0MALoEqgds=\n-----END PRIVATE KEY-----\n"
client_email = "streamlit-pnanyfc2025@pnany-fall-conference-2025.iam.gserviceaccount.com"
client_id = "101314842171780577380"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-pnanyfc2025%40pnany-fall-conference-2025.iam.gserviceaccount.com"

[course]
org_name       = "The Philippine Nurses Association of New York, Inc."
course_title   = "Lead to INSPIRE Fall Conference 2025 — Gabay at Galing: Empowering the New Generation of Nurse Leaders"
course_date    = "October 18, 2025"
credit_hours   = 4.75
passing_score  = 75

[sheets]
sheet_id = "1ofauJsfNEAX1Bnxrg9UMwgAnezlJsB20J685o8Re_kA"
eval_tab = "EvalandPT"
cert_tab = "Certificates"

